In [1]:
#bag of word model
corpus= [
    'UNC played Duke in basketball',
    'Duke lost the basketball game'
]
corpus.append('I ate a sandwich')

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()
print(vectorizer.fit_transform(corpus).todense())
print(vectorizer.vocabulary_)

[[0 1 1 0 1 0 1 0 0 1]
 [0 1 1 1 0 1 0 0 1 0]
 [1 0 0 0 0 0 0 1 0 0]]
{'unc': 9, 'played': 6, 'duke': 2, 'in': 4, 'basketball': 1, 'lost': 5, 'the': 8, 'game': 3, 'ate': 0, 'sandwich': 7}


In [3]:
from sklearn.metrics.pairwise import euclidean_distances
X=vectorizer.fit_transform(corpus).todense()
print('Distance between 1st and 2nd documents:', euclidean_distances(X[0],X[1]))
print('Distance between 1st and 3rd documents:',euclidean_distances(X[0],X[2]))
print('Distance between 2nd and 3rd documents', euclidean_distances(X[1],X[2]))
#Plus la distance est petite plus ils sont proches

Distance between 1st and 2nd documents: [[2.44948974]]
Distance between 1st and 3rd documents: [[2.64575131]]
Distance between 2nd and 3rd documents [[2.64575131]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-

In [4]:
vectorizer=CountVectorizer(stop_words='english')
print(vectorizer.fit_transform(corpus).todense())
print(vectorizer.vocabulary_)

[[0 1 1 0 0 1 0 1]
 [0 1 1 1 1 0 0 0]
 [1 0 0 0 0 0 1 0]]
{'unc': 7, 'played': 5, 'duke': 2, 'basketball': 1, 'lost': 4, 'game': 3, 'ate': 0, 'sandwich': 6}


In [5]:
from nltk.stem import WordNetLemmatizer
#from nltk.corpus import wordnet 
lemmatizer=WordNetLemmatizer()
print(lemmatizer.lemmatize('gathering','v'))
print(lemmatizer.lemmatize('gathering','n'))


gather
gathering


In [6]:
from nltk import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem.wordnet import WordNetLemmatizer
from nltk import pos_tag

In [7]:
wordnet_tags=['n','v']
corpus=[
    'He ate the sandwiches',
    'Every sandwich was eaten by him'
]
stemmer=PorterStemmer()
print('Stemmed:',[[stemmer.stem(token)for token in word_tokenize(document)] for document in corpus])


Stemmed: [['he', 'ate', 'the', 'sandwich'], ['everi', 'sandwich', 'wa', 'eaten', 'by', 'him']]


In [8]:
def lemmatize(token,tag):
    if tag[0].lower() in ['n','v']:
        return lemmatizer.lemmatize(token,tag[0].lower())
    return token

In [9]:
lemmatizer=WordNetLemmatizer()
tagged_corpus=[pos_tag(word_tokenize(document)) for document in corpus]
print('Lemmatized:',[[lemmatize(token,tag) for token,tag in document] for document in tagged_corpus])


Lemmatized: [['He', 'eat', 'the', 'sandwich'], ['Every', 'sandwich', 'be', 'eat', 'by', 'him']]


In [10]:
#Extending-bag-of-words with tf-idf weights

import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

corpus=[
    'The dog ate a sandwich, the wizard transfigured a sandwich, and I ate a sandwich'
]
vectorizer= CountVectorizer(stop_words='english')
frequencies= np.array(vectorizer.fit_transform(corpus).todense())[0]
print(frequencies)
print('Token indices %s' % vectorizer.vocabulary_)
for token, index in vectorizer.vocabulary_.items():
    print('Th token "%s" appears %s times' %(token, frequencies[index]))

[2 1 3 1 1]
Token indices {'dog': 1, 'ate': 0, 'sandwich': 2, 'wizard': 4, 'transfigured': 3}
Th token "dog" appears 1 times
Th token "ate" appears 2 times
Th token "sandwich" appears 3 times
Th token "wizard" appears 1 times
Th token "transfigured" appears 1 times


In [11]:
print(vectorizer.fit_transform(corpus).todense())

[[2 1 3 1 1]]


In [12]:
#TFIDF
from sklearn.feature_extraction.text import TfidfVectorizer
corpus=[
    'The dog ate a sandwich and I ate a sandwich',
    'The wizard transfigured a sandwich'
]
vectorizer=TfidfVectorizer(stop_words='english')
print(vectorizer.fit_transform(corpus).todense())

[[0.75458397 0.37729199 0.53689271 0.         0.        ]
 [0.         0.         0.44943642 0.6316672  0.6316672 ]]
